apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ia-clair.fullname" . }}
  labels:
    {{- include "ia-clair.labels" . | nindent 4 }}
data:
  AI_PROVIDER: {{ .Values.env.AI_PROVIDER | quote }}
