{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ia-clair.fullname" . }}
  labels:
    {{- include "ia-clair.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.SECRET_KEY }}
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.OPENAI_API_KEY }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.GEMINI_API_KEY }}
  GEMINI_API_KEY: {{ .Values.secrets.GEMINI_API_KEY | quote }}
  {{- end }}
  {{- if .Values.secrets.GEMINI_MODEL }}
  GEMINI_MODEL: {{ .Values.secrets.GEMINI_MODEL | quote }}
  {{- end }}
{{- end }}
